### ISSUE TITLE
Terraform lint inconsistencies 

### ISSUE THREAD

**Issue by ghost** [Azure/Azure-Verified-Modules-Grept#65]
- Currently the lint tool forces the role_assignment variable to include the condition and condition_version parameter, which is not supported by most services. As far as I know, only the storage account resource supports ABAC. This makes the modules fragile as if someone specifies something there the deployment will fail (We can always ignore whatever the user put there but it will be still confusing for the user to have a parameter that is always ignored). In my opinion, we should not force those two parameters as it is more common to have problems than actually use them to do something useful.
- For Customer managed keys, the AVM web pages suggest a structure ([see here](https://azure.github.io/Azure-Verified-Modules/specs/shared/interfaces/#customer-managed-keys)) while the avm-template repository has another one ([see here](https://github.com/Azure/terraform-azurerm-avm-template/blob/main/variables.tf#L22)). In my opinion, the correct one should be the one that is in the avm-template repository since to enable a CMK it is mandatory to specify the user managed identity resource id (Even the storage account module is doing something that conflicts with the tflint [see here](https://github.com/Azure/terraform-azurerm-avm-res-storage-storageaccount/blob/main/variables.tf#L17)). Should we create a user managed identity if one is not specified and comply with the tflint or should we do what the old modules do?
- Off topic. Could we have the "concurrency" parameter in the e2e tests github workflow? It is not a blocker, but it helps when doing multiple commits and the tf e2e tests are running. So pending ones are cancelled and we dont have to do it manually or wait for all of them to run.

**Comment by matt-FFFFFF** [comment]
Hi!

Thanks for reporting this.

We will look into you point 1.

As for point 2, the AVM spec is correct as it provides security when a supplied resource id is not known u til after apply.

In the above case it's not possible to use this value in a count expression.

Wrapping it in an object means we can test for the object being null, or not without knowing the resource id.

See: https://azure.github.io/Azure-Verified-Modules/specs/terraform/#id-tfnfr11---category-code-style---null-comparison-toggle

**Comment by matt-FFFFFF** [comment]
On your last point, there should be environment approvals set up to control deployments for e2e. Is this not happening?

**Comment by ghost** [comment]
I'm sorry but I didn't quite pick up your explanation for the 2do point. 

Just to make sure we are on the same page. I'm complaining about this specific null as it doesn't make sense in most cases (not just in my modules). That parameter in my opinion should be mandatory as for example the storage account is doing it.

![image](https://github.com/Azure/Azure-Verified-Modules-Grept/assets/117635118/cc2e0b48-b53d-4244-8a4e-85dd98da8029)

If someone doesn't specify the parameter "user_assigned_identity" then its default value would be null as per the AVM specification. Then, if this is the case how am I going to configure a CMK without this id? In my case in the SB and CosmosDB this value is mandatory and cannot be null or be a system assigned MI. The user must provide it. I'm very sure this is the case for most resouces in Azure as well. I'm already toggling depending on the variable value "customer_managed_key" but in my opinion it is also overkill to have to check for the "user_assigned_identity" parameter value as it is supposed to be mandatory if "customer_managed_key" is not null.

For the 3 point. I do have the deployment approval. But, I am suggesting an improvement since having a concurrency in the workflow means that if for some reason I make multiple commits (lets say 5) while one workflow is running/pending all the intermediate runs 1,2,3,4 will be automatically canceled and only the 5th one will be waiting for the current run to finish. For example, I recently had to manually cancel like 40 runs because they were all pending to run (I had problems with the runners in my repo). If I had had this concurrency those 39 runs would have been automatically cancelled for me.

**Comment by ghost** [comment]
For customer managed key the optional makes sense for those services which allows system managed identity. 
See: https://github.com/Azure/Azure-Verified-Modules/pull/72 

The object wrapping is a fix to an edge case when using datas
See: https://github.com/Azure/Azure-Verified-Modules/pull/623/files

**Comment by matt-FFFFFF** [comment]
Thanks - we will close this now

**Comment by ghost** [comment]
There is still the suggestions regarding the "conditions" in "role assignments"

**Comment by matt-FFFFFF** [comment]
Sorry - role assignment conditions

We must have these fields in the interface - I don't see any other way, do you?

**Comment by ghost** [comment]
Well, taking into consideration the result of the conversation we just had in our internal team regarding the "infrastructure_encryption" parameter. This means that this "condition" parameters should be a separate variable as it is only used by the storage account. Even less than the infrastructure encryption which is supported by multiple services

**Comment by matt-FFFFFF** [comment]
Thinking about the `map(object(...))` schema, it would appear clumsy to split this out. You would need another map of objects.

I do get your point about these attributes being unnecessary, but I have just implemented them as per the spec and nobody has complained

**Comment by matt-FFFFFF** [comment]
Also constrained delegation also uses these attributes:

https://learn.microsoft.com/en-us/azure/role-based-access-control/delegate-role-assignments-overview?tabs=azure-powershell#how-to-delegate-role-assignment-management-with-conditions

These can be universal
